name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the game-client Docker image
        run: docker build game-client --file game-client/Dockerfile --tag game-client:latest

      - uses: actions/checkout@v4
      - name: Build the game-server Docker image
        run: docker build game-server --file game-client/Dockerfile --tag game-server:latest
