name: Makefile CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # - name: configure
      # run: ./configure

      - name: Install dependencies
        run: make install

      - name: Run build
        run: make build
